DATA_TYPE: "EXP"


SAR_SETTINGS:
  SAR_Type: "Source_One_V5"
  SAR_Config: "A15_L250"

  # Policy_Type: "PARAM_OPTIM"
  # Policy_Type: "DEEP_RL_SB3" 
  Policy_Type: "DEEP_RL_ONBOARD" 
  
CAM_SETTINGS:
  Cam_Config: "None"
  Cam_Active: False


PLANE_SETTINGS: # INITIAL PLANE POSE SETTINGS
  Plane_Type: "Landing_Surface"
  Plane_Config: "Checkerboard_L02"
  Plane_Angle_init: 0  # [deg]
  Pos_X_init: 5.50    # [m]
  Pos_Y_init: 0.0    # [m]
  Pos_Z_init: 2.64    # [m]


SAR_DC_SETTINGS:
  Logging_Rate: 10 # [Hz]
