DATA_TYPE: "EXP"


SAR_SETTINGS:
  SAR_Type: "Source_One_V5"
  SAR_Config: "A15_L200"

  Policy_Type: "PARAM_OPTIM"
  # Policy_Type: "DEEP_RL_SB3" 
  # Policy_Type: "DEEP_RL_ONBOARD" 
  
CAM_SETTINGS:
  Cam_Config: "None"
  Cam_Active: False


PLANE_SETTINGS: # INITIAL PLANE POSE SETTINGS
  Plane_Model: "Standard_Plane"
  Plane_Angle: 0  # [deg]
  Pos_X: 5.30    # [m]
  Pos_Y: 0.0    # [m]
  Pos_Z: 2.54    # [m]


SAR_DC_SETTINGS:
  Logging_Rate: 10 # [Hz]
