DATA_TYPE: "EXP"

# ENV_SETTINGS:

PLANE_SETTINGS:
  Plane_Model: "Standard_Plane"
  Plane_Config: "180_deg"

QUAD_SETTINGS:
  CF_Type: "Standard"
  CF_Config: "A20_L75_K32"
  Cam_Sensor: False

  Policy_Type: "PARAM_OPTIM"
  # Policy_Type: "SVL_POLICY" 
  # Policy_Type: "DEEP_RL" 
  # Policy_Type: "DEEP_RL_SB3" 


CF_DC_SETTINGS:
  Console_Rate: 50 # [Hz]
  Logging_Rate: 10 # [Hz]






